# Generated by Django 3.0.7 on 2020-06-10 16:02

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields
import geo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('description', models.CharField(max_length=2500)),
                ('geo', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('url', easy_thumbnails.fields.ThumbnailerImageField(upload_to=geo.models.UploadToPathAndRename(''))),
                ('point', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.Point')),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('url', models.URLField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('point', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.Point')),
            ],
        ),
    ]
